### ISSUE TITLE
java.lang.NullPointerException: null value in entry: hibernate-entitymanager=null

### ISSUE THREAD

**Issue by infprime** [scottescue/dropwizard-entitymanager#37]
Hi trying to create a UnitOfWorkAwareProxyFactory is throwing the following exception. Looks like I may have not configured this correctly. Could you please help.
```
Exception in thread "main" java.lang.NullPointerException: null value in entry: hibernate-entitymanager=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33)
	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:50)
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:122)
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:197)
	at com.scottescue.dropwizard.entitymanager.UnitOfWorkAwareProxyFactory.<init>(UnitOfWorkAwareProxyFactory.java:30)
	at ..
```

I'm creating my EntityManagerBundle as (com.package has one `@Entity`)

```
	private final EntityManagerBundle<ReutersDataConfig> entityManagerBundle = 
			new ScanningEntityManagerBundle<ReutersDataConfig>("com.package") {
		@Override
		public DataSourceFactory getDataSourceFactory(ReutersDataConfig configuration) {
			return configuration.getDataSourceFactory();
		}
		
	};
```

**Comment by infprime** [comment]
I hadn't added the EntityManagerBundle in the `initialize` method. It works fine now. Thanks

**Comment by scottescue** [comment]
I'm glad you got it working, but that stack trace isn't very helpful. I'd prefer that to include a message that would help diagnose the problem.

Thanks for pointing this out.
